const Application = {
  statusCode: 200,
  statusMessage: "Success",
  data: {
    applicationId: "1326729612",
    jobId: "657878809",
    connectionStatus: "not_connected",
    previousConnectionStatus: "",
    connectionRemark: "",
    connectedAt: null,
    leadCreatedAt: "2024-06-12T03:38:15.130617Z",
    hiringState: "new_candidate",
    employerFeedback: "",
    userId: "16855780",
    fullName: "Nikhil Prasad",
    gender: "m",
    dateOfBirth: "2001-12-25T18:30:00Z",
    photoUrl: "profile_photo/16855780_1631171784563",
    area: "Jagdev Nagar",
    city: "Arrah",
    location: {
      displayName: "Jagdev Nagar, Arrah, BR",
      cityId: "64e4ad5ec35bd44248ca6e99",
      cityName: "Arrah",
      areaId: "64e4b7ccc35bd44248cbc5e6",
      areaName: "Jagdev Nagar",
      districtName: null,
      subDistrictId: "",
      subDistrictName: "",
      stateCode: "BR",
      stateName: "Bihar",
      countryName: "India",
    },
    totalExpInYears: "6yrs 3mos",
    salary: "Not disclosed",
    currentSalary: 0,
    experiences: [
      {
        id: "63adce2089a5b42801250a64",
        jobTitle: "Telecaller Cum Computer Operator",
        organisationTitle: "divya kit",
        start: "2018-05-31T18:30:00Z",
        end: "2019-02-28T18:30:00Z",
        ongoing: false,
        noticePeriod: "",
        industry: "Business Supplies \u0026 Equipment",
        role: "Data Entry/Computer Operator",
        department: "",
        departments: null,
      },
      {
        id: "6608e5aa71f6f4a5affb065c",
        jobTitle: "Data Entry Operator",
        organisationTitle: "shuddhi developers",
        start: "2018-05-31T18:30:00Z",
        end: "2019-02-28T18:30:00Z",
        ongoing: false,
        noticePeriod: "",
        industry: "Business Supplies \u0026 Equipment",
        role: "Data Entry/Computer Operator",
        department: "",
        departments: null,
      },
      {
        id: "6608e620850ef64f6b7b07a5",
        jobTitle: "Data Entry Operator",
        organisationTitle: "shuddhi Ayurweda",
        start: "2018-05-31T18:30:00Z",
        end: "2019-02-28T18:30:00Z",
        ongoing: false,
        noticePeriod: "",
        industry: "Business Supplies \u0026 Equipment",
        role: "Data Entry/Computer Operator",
        department: "",
        departments: null,
      },
    ],
    educations: [
      {
        level: "Graduate",
        courseTitle: "B.sc Math ( Hons.)",
        educationInstitute: "P.K. Roy Memorial College, Dhanbad    ",
        specialisation: "Math",
        start: "2019-07-31T18:30:00Z",
        end: "2022-09-30T18:30:00Z",
      },
      {
        level: "Graduate",
        courseTitle: "B.sc Math ( Hons.)",
        educationInstitute: "P.K. Roy Memorial College, Dhanbad    ",
        specialisation: "Math",
        start: "2019-07-31T18:30:00Z",
        end: "2022-09-30T18:30:00Z",
      },
      {
        level: "Graduate",
        courseTitle: "B.Sc",
        educationInstitute: "P.K. Roy Memorial College, Dhanbad    ",
        specialisation: "Mathematics",
        start: "2019-07-31T18:30:00Z",
        end: "2022-09-30T18:30:00Z",
      },
    ],
    language: {
      english: {
        highlight: false,
        proficiency: "good",
        audio_url:
          "https://cdn.apna.co/en_audio_assessment/16855780_1716207219",
      },
      regional: ["Hindi"],
    },
    skills: [
      "Basic Computer",
      "Customer service",
      "Database management",
      "Good Communication Skills",
      "Data entry",
    ],
    assetsAndDocs: ["Laptop", "Wifi", "Smartphone"],
    industries: ["Business Supplies \u0026 Equipment"],
    departments: ["Admin / Back Office / Computer Operator"],
    candidatePreferences: [
      "Day Shift",
      "Full Time",
      "Part Time",
      "Work from Home",
      "Work from Office",
    ],
    email: "nikmaurya61@gmail.com",
    resume: {
      url: "https://cdn.apna.co/resume/16855780_1711858943",
      format: "pdf",
      source: "PROFILE",
    },
    appliedOn: "2024-06-12T03:38:15.130617Z",
    priority: true,
    phoneNumber: "",
    candidateLastActiveAt: "2024-06-16T04:15:50Z",
    employerActions: {
      numberShown: false,
      shortlisted: false,
      rejected: false,
      callStatus: "",
      shortlistStatus: "",
      rejectedStatus: "",
    },
    candidateActions: "",
    profilePhotoUrl: "profile_photo/16855780_1631171784563",
    matchedCandidate: true,
    matchingCandidateParams: [
      "Work experience",
      "Language",
      "Salary",
      "Location",
      "Age",
    ],
  },
  httpStatusCode: 200,
};
export default Application;
